# Generated by Django 5.0.1 on 2024-01-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_pedidos_abono_pedidos_detalle_pedidos_entregado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='envio',
        ),
    ]
